routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear/to', function () {
  Artisan::call('cache:clear');
  Artisan::call('config:clear');
  Artisan::call('config:cache');
  Artisan::call('view:clear');
  return "Cleared!";
});



Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::post('/subscribe/', 'HomeController@subscribe')->name('newsletter.subscribe');

Route::prefix('admin')->as('admin.')->group(function() {
Route::get('/dashboard',['as' => 'dashbord','uses' =>'DashbordController@showForm'])->middleware(['auth']);
Route::get('/newsletter/create',['as' => 'newsletter.create','uses' =>'DashbordController@create'])->middleware(['auth']);
Route::post('/newsletter/store',['as' => 'newsletter.store','uses' =>'DashbordController@store'])->middleware(['auth']);

Route::post('/newsletter/send',['as' => 'newsletter.send','uses' =>'DashbordController@send'])->middleware(['auth']);

});

app/Newsletter.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Newsletter extends Model
{
    
    protected $guard = 'newsletters';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'titre', 'description'
    ];
    
    /**
     * The users that belong to the role.
     */
    public function users()
    {
        return $this->belongsToMany(User::class);
    }
 
}

app/NewsletterUser.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class NewsletterUser extends Model
{
    
    protected $guard = 'abonnements';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'newsletter_id'
    ];
    
 
 
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','gard'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

     public function getGuard(){
        return $this->guard;
    }

    /**
     * The roles that belong to the user.
     */
    public function newsletters()
    {
        return $this->belongsToMany(Newsletter::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashbordController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\User;
use App\Newsletter;
use App\NewsletterUser;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendNewsLetter;


class DashbordController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function showForm()
    {

        
        $newsletters=array();

        $newsletters=Newsletter::get();

        return view('admin.addnewsletter',compact('newsletters'));
    }


    /**
     * Create newsletter.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function create()
    {

        
        return view('admin.create',compact('newsletters'));
    }
   /**
     * store newsletter.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function store(Request $request)
    {

     $userObj = Auth::user();

     $fields=[
                'titre' => 'required',
                'description' => 'required',
               
            ];
  
    $request->validate(
             $fields
        );


    $arr['titre']              = $request->titre;
    $arr['description']              = $request->description;


    $register  = Newsletter::create($arr);

    if($register){
         return redirect()->back()->with('success', __('Newsletter crée avec succes !'));
    }
    else{
          return redirect()->back()->with('error', __('Une erreur est survenue !'));
    }
             

    }


   /**
     * send newsletter.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function send(Request $request)
    {
   

       $idnewsLetter= $request->id;

       $newsletter=Newsletter::find($idnewsLetter);

       if($newsletter){

         $users = User::select(['users.*','newsletter_users.newsletter_id'])
        ->join('newsletter_users', 'users.id', '=', 'newsletter_users.user_id')
        ->where('newsletter_users.newsletter_id', '=', $idnewsLetter)
        ->get();

        $listMail=array();

        foreach ($users as $key => $value) {
            
        try {
            
            Mail::to($value->email)->send(new SendNewsLetter($value,$newsletter->titre));
        } catch (\Exception $e) {
            
        }
        }
     
       }

       $resultat = [
            'success' => 1,
        ];
        return  response()->json($resultat);
     
    }

     

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Newsletter;
use App\NewsletterUser;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendValidationDetail;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the list newsletter.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        
        $newsletters=Newsletter::get();
        $message='';

        return view('home',compact('newsletters','message'));
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function subscribe(Request $request)
    {
        
     $fields=[
                'name' => 'required',
                'email' => 'required|email',
                'idnewsletter' => 'required',
            ];
  
    $request->validate(
             $fields
        );



    $user=User::where('email',$request->email)->first();
 
    if(!$user and empty($user->id)){


    $arrUser['name']              = $request->name;
    $arrUser['email']              = $request->email;
    $arrUser['password']    = Hash::make('1234');
    $arrUser['gard']        = 'client';
    $user           = User::create($arrUser);

    $user->remember_token = $remember_token = Str::random(60);
    $user->save();      
    }

    $newsletters=Newsletter::find($request->idnewsletter);
    // save subscrib

    $issubscibed=NewsletterUser::where('user_id',$user->id)->where('newsletter_id',$request->idnewslette)->first();
 
     if(!$issubscibed or empty($issubscibed->id)){
         
        $arr['newsletter_id']              = $request->idnewsletter;
        $arr['user_id']              = $user->id;
        $NewsletterUser           = NewsletterUser::create($arr);


        try {

            Mail::to($user->email)->send(new SendValidationDetail($user,$newsletters->titre));
            
        } catch (\Exception $e) {
            
        }

        $message="<span class='badge badge-success'>Vous avez été inscrit avec succès à la Newsletter</span>";
         
     }
     else{
        
         $message="<span class='badge badge-danger'>Vous êtes déja abonné à cet newsletter.</span>";
     }

     $newsletters=Newsletter::get();

      return view('home',compact('newsletters','message'));
    
  
    }


}

resources/views/admin/addnewsletter.blade.php
@extends('layouts.layout-admin')
@section('page-title') {{__('Liste newsletters')}} @endsection

@section('content')


 <div class="subheader py-2 py-lg-4 subheader-solid   " id="kt_subheader">
              <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-2">
                  <!--begin::Page Title-->
                  <h5 class="text-dark font-weight-bold my-1 mr-5">{{__('Liste des clients')}}</h5>
                  <!--end::Page Title-->
                </div>
                <!--end::Info-->
                <!--begin::Toolbar-->
                <div class="d-flex align-items-center">
                  <!--begin::Dropdowns-->
                  <div class="dropdown dropdown-inline" data-toggle="tooltip" title="" data-placement="left" data-original-title="Créer un nouveau client">
                   
                   <button type="button" class="btn btn-primary btn-rounded " data-ajax-popup="true" data-size="lg" data-title="Créer une newsletter" data-url="{{route('admin.newsletter.create')}}">
                                <i class="mdi mdi-plus"></i> {{__('Créer ')}}
                   </button>
                
                  </div>
                </div>
                <!--end::Toolbar-->
              </div>
</div>
<div id="kt_datatable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer" style="margin-top: 100px">
<div class="row">
  <div class="col-md-12">
       <div class="card card-custom gutter-b">
      
              <!-- /.card-header -->
              <div class="card-body">
                <table  id="datatable" class="table table-separate datatable-client table-head-custom table-checkable dataTable no-footer dtr-inline mb-0 animated ">
                  <thead>
                  <tr>
                    
                    <th class="dt-left sorting_disabled"></th>
                    <th>{{ __('Titre')}}</th>
                    <th>{{ __('Description')}}</th>
                    <th>{{ __('Actions')}}</th>
                  </tr>
                  </thead>
                  <tbody>


                     @foreach ($newsletters as $val)
                    <tr>
                    <td class="dt-left sorting_disabled" rowspan="1" colspan="1" style="width: 35px;" aria-label=" ID">
                    <label class="checkbox checkbox-single">
                        <input type="checkbox" value="{{$val->id}}" class="group-checkable">
                        <span></span>
                    </label></td>
                    <td> {{$val->titre}}</td>
                    <td>{{$val->description}}</td>

                    <td>
                      <a href="#" class="btn btn-primary" id="sendmail" data="{{$val->id}}">
                          envoyer une newsletter  
                          <span style="display: none" id="loading" class="badge btn-danger">EN cours...</span>
                      </a>
                    </td>

                  </tr>

                     @endforeach
                    
   
                  
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
  </div>
</div>
</div>
 
 <input type="hidden" id="baseurl" value="{{route('admin.newsletter.send')}}">
@endsection

@push('scripts')

 
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatable_filter').append('<div class="btnremove btn-group"><input class="checkall" type="checkbox" onclick="checkAll(this)"  /> <button type="button"  onclick=\'(confirm("Êtes-vous sûr ?")?document.getElementById("delete-all").submit(): "");\' class="btn btn-danger btn-rounded " >Supprimer</button></div>')
  })
  
</script>
 

<script type="text/javascript">
	$(document).ready(function(){
		$('#datatable_filter').prepend('<div style="display: none;" class="btnfiltre btn-group"><button type="button" class="btn btn-primary btn-rounded " >Filtre</button></div>');
		$('#datatable_filter label').contents().filter(function() {
    return this.nodeType == 3
}).each(function(){
    this.textContent = '';
});
		
	})
	
</script>
@endpush

resources/views/admin/create.blade.php
<form class="pl-3 pr-3 formcls" method="post" action="{{ route('admin.newsletter.store') }}">
    @csrf
 
    <div class="form-group">
        <div class="row">
            <div class="col-md-6">
                <label for="">*{{ __('Titre') }}</label>
                <input class="form-control" type="text" id="" name="titre" value=""  placeholder=""  >
            </div> 
          
         
        </div>
        <div class="row">
              <div class="col-md-4">
                <label for="">*{{ __('Description') }}</label>
                <textarea class="form-control" required="" name="description" placeholder="Description" ></textarea>   
            </div> 
        </div>
    </div>

 
    <div class="form-group tright">
        <button class="btn btn-primary" type="submit">{{ __('Créer ') }}</button>
    </div>
 
</form>
 
 

resources/views/front/listeNewsLetter.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <h1>Liste des newsletters</h1>

    @if ($message)
        {!! $message !!}
    @endif
    <br><br>
    <div class="row justify-content-center" style="width: 100%">

        <div class="col-md-12">
            @foreach ($newsletters as $val)
             
            <div class="card row">
                <div class="col-md-3">
                    <img src="">
                </div>
                <div class="col-md-9">
                     <h2>{{$val->titre}}</h2>
                     <p>{{$val->description}}</p>
                     <p>
                          <button type="button" class="btn btn-primary" id="subscribbtn" data="{{$val->id}}" data-toggle="modal" data-target="#newslettersModal">Je m'abonne</button>
                     </p>
                </div>
            </div>
            
            @endforeach
        </div>

        
    </div>
</div>

<div class="modal" id="newslettersModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
 
    <div class="modal-content">
    <form action="{{route('newsletter.subscribe')}}" method="post">
 @csrf
      <div class="modal-header">
        <h5 class="modal-title">Inscription à la newsletter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
      <div class="row">

              <div class="col-md-12">
                  <input type="text" class="form-control" name="name" id="name" placeholder="Votre nom.." required="">

              </div>
            
       </div>

        <div class="row">

              <div class="col-md-12">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Votre email.." required="">

              </div>
            
        </div>

       
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Valider</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <input type="hidden" name="idnewsletter" id="idnewsletter">
      </div>
       </form>
    </div>
  </div>
</div>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/app/custom.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
     <!-- App css -->
    <link href="{{ asset('public/assets/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/css/components.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('public/assets/css/iziToast.min.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <div id="app" style="overflow: hidden;">
        <nav class=" bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @yield('content')
        </main>
    </div>


    <!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{ asset('public/assets/js/stisla.js') }}"></script>

<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{{ asset('public/assets/js/scrollreveal.min.js') }}"></script>
<script src="{{ asset('public/assets/js/scripts.js') }}"></script>
{{--<script src="{{ asset('public/assets/js/custom.js') }}"></script>--}}
<script src="{{ asset('public/vendor/dist/js/iziToast.min.js') }}"></script>

@stack('scripts')
@if ($message = Session::get('success'))
    <script>toastr('{{__('Success')}}', '{!! $message !!}', 'success')</script>
@endif

@if ($message = Session::get('error'))
    <script>toastr('{{__('Error')}}', '{!! $message !!}', 'error')</script>
@endif

@if ($message = Session::get('info'))
    <script>toastr('{{__('Info')}}', '{!! $message !!}', 'info')</script>
@endif
@if ($message = Session::get('warning'))
    <script>toastr('{{__('Warning')}}', '{!! $message !!}', 'warning')</script>
@endif

</body>
</html>

resources/views/layouts/base/_aside.blade.php
{{-- Aside --}}
 
<style>
    .disableClick {pointer-events: none;}
</style>
<div class="aside aside-left   d-flex flex-column flex-row-auto" id="kt_aside">

    {{-- Brand --}}
    <div class="brand flex-column-auto  " id="kt_brand">
        <div class="brand-logo">
            <a href="{{ url('/') }}">
                
                
            </a>
        </div>

      
            <button class="brand-toggle btn btn-sm px-0" id="kt_aside_toggle">
                 
            </button>
       

    </div>

    {{-- Aside menu --}}
    <div class="aside-menu-wrapper flex-column-fluid" id="kt_aside_menu_wrapper">

        @if (config('layouts.aside.self.display') === false)
            <div class="header-logo">
                <a href="{{ url('/') }}">
                    <img alt="{{ config('app.name') }}" src="{{ asset('media/logos/'.$kt_logo_image) }}"/>
                </a>
            </div>
        @endif


    <div class="user-panel mt-3  d-flex">
          <!-- select client Form -->
      
      </div>

        <div
            id="kt_aside_menu"
            class="aside-menu my-4  "
            data-menu-vertical="1"
            >

            <ul class="menu-nav  ">
                <li class="menu-item menu-item-active" aria-haspopup="true">
                                    <a href=" " class="menu-link">
                                        
                                             
                                             <span class="menu-text">{{ __('Dashboard')}}</span>
                                        
                                    </a>
               </li>

 
 
                                        </ul>
                                    </div>
                                </li>
 


            </ul>
        </div>
    </div>

</div>
 

resources/views/layouts/base/_content.blade.php
{{-- Content --}}
@if (config('layouts.content.extended'))
    @yield('content')
@else
    <div class="d-flex flex-column-fluid">
        <div class="" style="    width: 100%;
    margin-left: 23%;
    margin-right: 10%;">
            @yield('content')
        </div>
    </div>
@endif

resources/views/layouts/partials/extras/_scrolltop.blade.php
{{-- Scrolltop --}}
<div id="kt_scrolltop" class="scrolltop">
	{{ Metronic::getSVG("media/svg/icons/Navigation/Up-2.svg") }}
	{{-- <i class="fa fa-arrow-up"></i> --}}
</div>

resources/views/layouts/partials/sidebar.blade.php
<style>
    .disableClick {pointer-events: none;}
</style>
   <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link brand-link-custom">
      <img src="{{asset('/public/storage/logo/logo-full.png')}}" alt=" " class="brand-image img-logo "  >
    </a>   <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <!-- select client Form -->
      <div class="form-inline full-with">
        <div class="input-group" data-widget="sidebar-search">
          <select class="form-control form-control-sidebar full-with" onChange="getInfosClient(this.value)">
            <option value="">Sélection du client</option>
            @foreach($data_customer_layouts as $val)
              <option value="{{$val->slug}}" 
                {{(Session::has('selected_client_slug') && Session::get('selected_client_slug') == $val->slug) ? 'selected':''}}
              >{{$val->lname.' '.$val->fname}} / {{$val->slug}}</option>
            @endforeach
          </select>
        </div>
      </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('admin.home') }}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>{{ __('Dashbord')}}</p>
            </a>
          </li>
        
          <li class="nav-item (Session::has('selected_client_slug') && Session::get('selected_client_slug') != '') ? '':'disableClick'">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                 {{__('Clients')}}
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right"></span>
              </p>
            </a>
            @if(Session::has('selected_client_slug'))
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('admin.client.infos.client', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Infos client')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.client.licences', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Licences')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.client.roles', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Rôles personnalisés')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.client.theme', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Thèmes')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.client.filtres', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Filtres')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('admin.client.connecteurs', Session::get('selected_client_slug'))}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{__('Connecteurs')}}</p>
                </a>
              </li>
            </ul>
            @endif
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
               {{ __('Paramètres global')}}
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('admin.client.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Clients')}}</p>
                </a>
              </li>
               <li class="nav-item">
                <a href="{{ route('admin.site.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Sites')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('admin.role.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Rôles')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('admin.utilisateur.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Utilisateurs')}}</p>
                </a>
              </li>
               <li class="nav-item">
                <a href="{{ route('admin.permission.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Permissions')}}</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('admin.smtp.list') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Smtp')}}</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                {{ __('Documentation')}}
               
              </p>
            </a>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  <script>
  function getInfosClient(slug){
      $.ajax({
            url:"{{ URL::to('/') }}/admin/client/storeSlug/"+slug,
            type: "GET",
        success: function(msg){
          if(slug != ''){
            window.location = "{{ URL::to('/') }}/admin/"+slug+"/infos-client"
          }
        }
      });
  }
  </script>